//  SPDX-FileCopyrightText: 2026 Aravinth-Earth
//  SPDX-License-Identifier: AGPL-3.0-or-later
package io.payanam.database

import androidx.room.Database
import androidx.room.RoomDatabase
import io.payanam.database.dao.AppSettingsDao
import io.payanam.database.dao.DailyInsightDao
import io.payanam.database.dao.DayPlanDao
import io.payanam.database.dao.DayMetricDao
import io.payanam.database.dao.HabitMetricDao
import io.payanam.database.dao.DimensionMetricDao
import io.payanam.database.dao.ImportBatchDao
import io.payanam.database.dao.JournalDao
import io.payanam.database.dao.LensReflectionDao
import io.payanam.database.dao.LifeDimensionDao
import io.payanam.database.dao.NoteDao
import io.payanam.database.dao.ScheduledNotificationDao
import io.payanam.database.dao.ScoringConfigDao
import io.payanam.database.dao.TagDao
import io.payanam.database.dao.TaskDao
import io.payanam.database.dao.TaskOccurrenceDao
import io.payanam.database.dao.TaskRescheduleDao
import io.payanam.database.dao.TimeEntryDao
import io.payanam.database.entity.AppSettingEntity
import io.payanam.database.entity.DailyInsightEntity
import io.payanam.database.entity.DayJournalEntryEntity
import io.payanam.database.entity.DayJournalResponseEntity
import io.payanam.database.entity.DayPlanAllocationEntity
import io.payanam.database.entity.DayPlanPolicyEntity
import io.payanam.database.entity.DayPlanTemplateAllocationEntity
import io.payanam.database.entity.DayPlanTemplateEntity
import io.payanam.database.entity.DayMetricEntity
import io.payanam.database.entity.DayTypeTemplatePreferenceEntity
import io.payanam.database.entity.HabitMetricEntity
import io.payanam.database.entity.DimensionMetricEntity
import io.payanam.database.entity.ImportBatchEntity
import io.payanam.database.entity.JournalNoteEntity
import io.payanam.database.entity.LensReflectionEntity
import io.payanam.database.entity.LifeDimensionEntity
import io.payanam.database.entity.NoteEntity
import io.payanam.database.entity.NoteTagEntity
import io.payanam.database.entity.ScheduledNotificationEntity
import io.payanam.database.entity.ScoringConfigEntity
import io.payanam.database.entity.TagEntity
import io.payanam.database.entity.TaskEntity
import io.payanam.database.entity.TaskOccurrenceEntity
import io.payanam.database.entity.TaskRescheduleEntity
import io.payanam.database.entity.TaskTagEntity
import io.payanam.database.entity.TimeEntryEntity
import io.payanam.database.entity.TimeEntryTagEntity
import io.payanam.database.entity.TimeGoalEntity
import io.payanam.database.entity.TimeRuleEntity
import io.payanam.database.entity.UserPreferenceEntity
const val PAYANAM_DATABASE_SCHEMA_VERSION = 21

/**
 * Room Database for Payanam.
 *
 * Schema version 17 - Habit recurrence system overhaul (uHabits-aligned).
 * - Removed task_occurrences.autoGenerated column (absence = implicitly missed)
 * - Removed tasks.recurrenceStrategy and tasks.dayBoundaryHour columns
 * - Converted all recurrenceRule values from CONFIG:/RRULE: to "num/den" format
 *
 * Schema version 16 - Day plan policy contract hardening.
 * - Added day_plan_policies table for per-day mode/template/starred policy
 * - Added day_type_template_preferences table for auto-template mappings
 *
 * Schema version 15 - Phase 7: Journal + Notes consolidation.
 * - Added journal_notes table for multi-entry freeform notes per day/dimension
 * - Migrated legacy notes rows into journal_notes
 *
 * Schema version 14 - Phase 6: Day Planning + Scoring.
 * - Added day_plan_templates table for reusable day plan presets
 * - Added day_plan_template_allocations table for template dimension entries
 * - Added day_plan_allocations table for per-day planned minutes per dimension
 *
 * Schema version 13 - Phase 4.5: Planning & Reality Lens.
 * - Added lens_reflections table for gap detection and reflection cards
 *
 * Schema version 12 - Phase-3 time parity foundation (tags/goals/rules).
 * - Added tags table + task/note/time_entry tag mapping tables
 * - Added time_goals and time_rules tables
 *
 * Schema version 11 - Recurring occurrence reason persistence.
 * - Added task_occurrences.statusReason to persist structured reason values.
 *
 * Schema version 10 - Day-key query foundation + insights cache.
 * - Added day_key columns to tasks/time_entries/notes with indexes
 * - Added daily_insights cache table
 *
 * Schema version 9 - Import metadata foundation.
 * - Added import_batches table
 * - Added import_source/import_id/imported_at/import_batch_id on tasks and time_entries
 *
 * Schema version 8 - Dimension foundation.
 * - Added life_dimensions table + Unassigned seed row
 * - Added user_preferences typed settings table
 * - Added dimension_id columns to tasks/time_entries/notes/day_journal_responses
 *
 * Schema version 7 - Focus tracking fields for time entries.
 * - Added focusRating, focusNote, focusRatedAt to time_entries
 *
 * Schema version 6 - Actual completion tracking.
 * - Added actualCompletedAt, actualDurationMinutes to task_occurrences
 *
 * Schema version 5 - Recurrence redesign with decay scoring.
 * - Added currentScore, lastOccurrenceDate, dayBoundaryHour to tasks
 * - Added autoGenerated to task_occurrences
 *
 * Note: When migrating from the Capacitor version, we'll need to handle
 * the existing SQLite database files. Room can open existing databases
 * if the schema matches.
 */
@Database(
    entities = [
        TaskEntity::class,
        TimeEntryEntity::class,
        NoteEntity::class,
        TaskOccurrenceEntity::class,
        TaskRescheduleEntity::class,
        DayJournalEntryEntity::class,
        DayJournalResponseEntity::class,
        JournalNoteEntity::class,
        DailyInsightEntity::class,
        AppSettingEntity::class,
        UserPreferenceEntity::class,
        ImportBatchEntity::class,
        ScheduledNotificationEntity::class,
        ScoringConfigEntity::class,
        LifeDimensionEntity::class,
        TagEntity::class,
        TaskTagEntity::class,
        NoteTagEntity::class,
        TimeEntryTagEntity::class,
        HabitMetricEntity::class,
        DimensionMetricEntity::class,
        DayMetricEntity::class,
        TimeGoalEntity::class,
        TimeRuleEntity::class,
        LensReflectionEntity::class,
        DayPlanTemplateEntity::class,
        DayPlanTemplateAllocationEntity::class,
        DayPlanAllocationEntity::class,
        DayPlanPolicyEntity::class,
        DayTypeTemplatePreferenceEntity::class,
    ],
    version = PAYANAM_DATABASE_SCHEMA_VERSION,
    exportSchema = true,
)
/**
 * Room database holding every Payanam entity (tasks, time entries, notes, occurrences,
 * journal, day plans, score metrics, lens reflections). Version is pinned to
 * [PAYANAM_DATABASE_SCHEMA_VERSION]; see the schema-history comment on the class
 * for what each version added.
 */
abstract class PayanamDatabase : RoomDatabase() {
    /** DAO for task rows + their occurrence/tag mappings. */
    abstract fun taskDao(): TaskDao
    /** DAO for tracked time entries and their focus/tag data. */
    abstract fun timeEntryDao(): TimeEntryDao
    /** DAO for notes and their tag/legacy-journal mappings. */
    abstract fun noteDao(): NoteDao
    /** DAO for per-day task occurrences (completed/skipped/missed). */
    abstract fun taskOccurrenceDao(): TaskOccurrenceDao
    /** DAO for recorded task reschedule events. */
    abstract fun taskRescheduleDao(): TaskRescheduleDao
    /** DAO for day journal entries + prompt responses + freeform journal notes. */
    abstract fun journalDao(): JournalDao
    /** DAO for key/value app settings. */
    abstract fun appSettingsDao(): AppSettingsDao
    /** DAO for scheduled notification rows. */
    abstract fun scheduledNotificationDao(): ScheduledNotificationDao
    /** DAO for the persisted scoring configuration. */
    abstract fun scoringConfigDao(): ScoringConfigDao
    /** DAO for life-dimension catalog (label/color/icon/weight). */
    abstract fun lifeDimensionDao(): LifeDimensionDao
    /** DAO for tags. */
    abstract fun tagDao(): TagDao
    /** DAO for lens reflection gap cards. */
    abstract fun lensReflectionDao(): LensReflectionDao
    /** DAO for the daily-insights cache (metric snapshots + dirty-day markers). */
    abstract fun dailyInsightDao(): DailyInsightDao
    /** DAO for day-plan allocations, templates, policies, type-preferences. */
    abstract fun dayPlanDao(): DayPlanDao
    /** DAO for import-batch metadata rows. */
    abstract fun importBatchDao(): ImportBatchDao
    /** DAO for habit-level (L1) score metrics. */
    abstract fun habitMetricDao(): HabitMetricDao
    /** DAO for dimension-level (L2) score metrics. */
    abstract fun dimensionMetricDao(): DimensionMetricDao
    /** DAO for day-level (L3) score metrics. */
    abstract fun dayMetricDao(): DayMetricDao

    companion object {
        const val DATABASE_NAME = "payanam.db"
    }
}
