//  SPDX-FileCopyrightText: 2026 Aravinth-Earth
//  SPDX-License-Identifier: AGPL-3.0-or-later
@file:Suppress("ktlint:standard:no-wildcard-imports")

package io.payanam.ui.model

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.ui.graphics.vector.ImageVector
import io.payanam.common.logging.UnifiedLogger
import io.payanam.domain.model.DimensionTaxonomyCatalog
import io.payanam.domain.model.LifeDimension
/**
 * Holds the dimension icon option.
 */
data class DimensionIconOption(
    val key: String,
    val imageVector: ImageVector,
)
object DimensionIconCatalog {
    private fun loggerOrNull(): UnifiedLogger? = runCatching { UnifiedLogger.getInstance() }.getOrNull()
    val options: List<DimensionIconOption> = listOf(
        DimensionIconOption("work", Icons.Outlined.WorkOutline),
        DimensionIconOption("favorite", Icons.Outlined.FavoriteBorder),
        DimensionIconOption("groups", Icons.Outlined.Groups),
        DimensionIconOption("trending_up", Icons.Outlined.TrendingUp),
        DimensionIconOption("account_balance_wallet", Icons.Outlined.AccountBalanceWallet),
        DimensionIconOption("self_improvement", Icons.Outlined.SelfImprovement),
        DimensionIconOption("sports_esports", Icons.Outlined.SportsEsports),
        DimensionIconOption("menu_book", Icons.Outlined.MenuBook),
        DimensionIconOption("volunteer_activism", Icons.Outlined.VolunteerActivism),
        DimensionIconOption("category", Icons.Outlined.Category),
        DimensionIconOption("fitness_center", Icons.Outlined.FitnessCenter),
        DimensionIconOption("hiking", Icons.Outlined.Hiking),
        DimensionIconOption("home", Icons.Outlined.Home),
        DimensionIconOption("psychology", Icons.Outlined.Psychology),
        DimensionIconOption("music_note", Icons.Outlined.MusicNote),
        DimensionIconOption("event", Icons.Outlined.Event),
        DimensionIconOption("schedule", Icons.Outlined.Schedule),
        DimensionIconOption("computer", Icons.Outlined.Computer),
        DimensionIconOption("restaurant", Icons.Outlined.Restaurant),
        DimensionIconOption("pets", Icons.Outlined.Pets),
        DimensionIconOption("child_care", Icons.Outlined.ChildCare),
        DimensionIconOption("eco", Icons.Outlined.Eco),
        DimensionIconOption("travel_explore", Icons.Outlined.TravelExplore),
        DimensionIconOption("public", Icons.Outlined.Public),
        DimensionIconOption("shield", Icons.Outlined.Shield),
        DimensionIconOption("local_cafe", Icons.Outlined.LocalCafe),
        DimensionIconOption("nightlight", Icons.Outlined.Nightlight),
        DimensionIconOption("directions_run", Icons.Outlined.DirectionsRun),
        DimensionIconOption("star_outline", Icons.Outlined.StarOutline),
        DimensionIconOption("bolt", Icons.Outlined.Bolt),
        DimensionIconOption("brush", Icons.Outlined.Brush),
        DimensionIconOption("build", Icons.Outlined.Build),
        DimensionIconOption("palette", Icons.Outlined.Palette),
        DimensionIconOption("bookmark_border", Icons.Outlined.BookmarkBorder),
        DimensionIconOption("lightbulb", Icons.Outlined.Lightbulb),
        DimensionIconOption("widgets", Icons.Outlined.Widgets),
        DimensionIconOption("rocket_launch", Icons.Outlined.RocketLaunch),
        DimensionIconOption("sports_soccer", Icons.Outlined.SportsSoccer),
        DimensionIconOption("headphones", Icons.Outlined.Headphones),
        DimensionIconOption("photo_camera", Icons.Outlined.PhotoCamera),
        DimensionIconOption("science", Icons.Outlined.Science),
        DimensionIconOption("medical_services", Icons.Outlined.MedicalServices),
        DimensionIconOption("monitor_heart", Icons.Outlined.MonitorHeart),
        DimensionIconOption("temple_hindu", Icons.Outlined.TempleHindu),
        DimensionIconOption("forest", Icons.Outlined.Forest),
        DimensionIconOption("park", Icons.Outlined.Park),
        DimensionIconOption("wb_sunny", Icons.Outlined.WbSunny),
        DimensionIconOption("dark_mode", Icons.Outlined.DarkMode),
        DimensionIconOption("keyboard", Icons.Outlined.Keyboard),
        DimensionIconOption("shopping_bag", Icons.Outlined.ShoppingBag),
        DimensionIconOption("payments", Icons.Outlined.Payments),
        DimensionIconOption("storefront", Icons.Outlined.Storefront),
        DimensionIconOption("flight", Icons.Outlined.Flight),
        DimensionIconOption("ramen_dining", Icons.Outlined.RamenDining),
        DimensionIconOption("lunch_dining", Icons.Outlined.LunchDining),
        DimensionIconOption("shopping_cart", Icons.Outlined.ShoppingCart),
        DimensionIconOption("local_florist", Icons.Outlined.LocalFlorist),
        DimensionIconOption("spa", Icons.Outlined.Spa),
        DimensionIconOption("theater_comedy", Icons.Outlined.TheaterComedy),
        DimensionIconOption("toys", Icons.Outlined.Toys),
        DimensionIconOption("mood", Icons.Outlined.Mood),
        DimensionIconOption("heart_broken", Icons.Outlined.HeartBroken),
        DimensionIconOption("help_outline", Icons.Outlined.HelpOutline),
        DimensionIconOption("cleaning_services", Icons.Outlined.CleaningServices),
        DimensionIconOption("inventory_2", Icons.Outlined.Inventory2),
        DimensionIconOption("language", Icons.Outlined.Language),
        DimensionIconOption("lock", Icons.Outlined.Lock),
        DimensionIconOption("handyman", Icons.Outlined.Handyman),
        DimensionIconOption("edit_note", Icons.Outlined.EditNote),
        DimensionIconOption("piano", Icons.Outlined.Piano),
        DimensionIconOption("explore", Icons.Outlined.Explore),
        DimensionIconOption("diversity_3", Icons.Outlined.Diversity3),
        DimensionIconOption("volcano", Icons.Outlined.Volcano),
        DimensionIconOption("abc", Icons.Outlined.Abc),
        DimensionIconOption("access_alarm", Icons.Outlined.AccessAlarm),
        DimensionIconOption("access_alarms", Icons.Outlined.AccessAlarms),
        DimensionIconOption("accessibility", Icons.Outlined.Accessibility),
        DimensionIconOption("accessibility_new", Icons.Outlined.AccessibilityNew),
        DimensionIconOption("accessible", Icons.Outlined.Accessible),
        DimensionIconOption("accessible_forward", Icons.Outlined.AccessibleForward),
        DimensionIconOption("access_time", Icons.Outlined.AccessTime),
        DimensionIconOption("access_time_filled", Icons.Outlined.AccessTimeFilled),
        DimensionIconOption("account_tree", Icons.Outlined.AccountTree),
        DimensionIconOption("ac_unit", Icons.Outlined.AcUnit),
        DimensionIconOption("adb", Icons.Outlined.Adb),
        DimensionIconOption("add_alarm", Icons.Outlined.AddAlarm),
        DimensionIconOption("add_alert", Icons.Outlined.AddAlert),
        DimensionIconOption("add_a_photo", Icons.Outlined.AddAPhoto),
        DimensionIconOption("add_box", Icons.Outlined.AddBox),
        DimensionIconOption("add_business", Icons.Outlined.AddBusiness),
        DimensionIconOption("add_card", Icons.Outlined.AddCard),
        DimensionIconOption("addchart", Icons.Outlined.Addchart),
        DimensionIconOption("add_home", Icons.Outlined.AddHome),
        DimensionIconOption("add_moderator", Icons.Outlined.AddModerator),
        DimensionIconOption("add_photo_alternate", Icons.Outlined.AddPhotoAlternate),
        DimensionIconOption("add_reaction", Icons.Outlined.AddReaction),
        DimensionIconOption("add_road", Icons.Outlined.AddRoad),
        DimensionIconOption("add_to_drive", Icons.Outlined.AddToDrive),
        DimensionIconOption("add_to_photos", Icons.Outlined.AddToPhotos),
        DimensionIconOption("add_to_queue", Icons.Outlined.AddToQueue),
        DimensionIconOption("adjust", Icons.Outlined.Adjust),
        DimensionIconOption("ad_units", Icons.Outlined.AdUnits),
        DimensionIconOption("agriculture", Icons.Outlined.Agriculture),
        DimensionIconOption("air", Icons.Outlined.Air),
        DimensionIconOption("airlines", Icons.Outlined.Airlines),
        DimensionIconOption("airline_stops", Icons.Outlined.AirlineStops),
        DimensionIconOption("airport_shuttle", Icons.Outlined.AirportShuttle),
        DimensionIconOption("alarm", Icons.Outlined.Alarm),
        DimensionIconOption("alarm_add", Icons.Outlined.AlarmAdd),
        DimensionIconOption("alarm_off", Icons.Outlined.AlarmOff),
        DimensionIconOption("alarm_on", Icons.Outlined.AlarmOn),
        DimensionIconOption("album", Icons.Outlined.Album),
        DimensionIconOption("align_horizontal_center", Icons.Outlined.AlignHorizontalCenter),
        DimensionIconOption("align_horizontal_left", Icons.Outlined.AlignHorizontalLeft),
        DimensionIconOption("align_horizontal_right", Icons.Outlined.AlignHorizontalRight),
        DimensionIconOption("all_inclusive", Icons.Outlined.AllInclusive),
        DimensionIconOption("all_out", Icons.Outlined.AllOut),
        DimensionIconOption("alt_route", Icons.Outlined.AltRoute),
        DimensionIconOption("amp_stories", Icons.Outlined.AmpStories),
        DimensionIconOption("analytics", Icons.Outlined.Analytics),
        DimensionIconOption("anchor", Icons.Outlined.Anchor),
        DimensionIconOption("android", Icons.Outlined.Android),
        DimensionIconOption("animation", Icons.Outlined.Animation),
        DimensionIconOption("announcement", Icons.Outlined.Announcement),
        DimensionIconOption("aod", Icons.Outlined.Aod),
        DimensionIconOption("apartment", Icons.Outlined.Apartment),
        DimensionIconOption("app_blocking", Icons.Outlined.AppBlocking),
        DimensionIconOption("app_registration", Icons.Outlined.AppRegistration),
        DimensionIconOption("approval", Icons.Outlined.Approval),
        DimensionIconOption("architecture", Icons.Outlined.Architecture),
        DimensionIconOption("area_chart", Icons.Outlined.AreaChart),
        DimensionIconOption("article", Icons.Outlined.Article),
        DimensionIconOption("assignment", Icons.Outlined.Assignment),
        DimensionIconOption("assignment_ind", Icons.Outlined.AssignmentInd),
        DimensionIconOption("assignment_late", Icons.Outlined.AssignmentLate),
        DimensionIconOption("assignment_return", Icons.Outlined.AssignmentReturn),
        DimensionIconOption("assignment_returned", Icons.Outlined.AssignmentReturned),
        DimensionIconOption("assignment_turned_in", Icons.Outlined.AssignmentTurnedIn),
        DimensionIconOption("assistant", Icons.Outlined.Assistant),
        DimensionIconOption("assistant_direction", Icons.Outlined.AssistantDirection),
        DimensionIconOption("assistant_photo", Icons.Outlined.AssistantPhoto),
        DimensionIconOption("assist_walker", Icons.Outlined.AssistWalker),
        DimensionIconOption("assured_workload", Icons.Outlined.AssuredWorkload),
        DimensionIconOption("atm", Icons.Outlined.Atm),
        DimensionIconOption("attractions", Icons.Outlined.Attractions),
        DimensionIconOption("attribution", Icons.Outlined.Attribution),
        DimensionIconOption("auto_awesome", Icons.Outlined.AutoAwesome),
        DimensionIconOption("auto_awesome_mosaic", Icons.Outlined.AutoAwesomeMosaic),
        DimensionIconOption("auto_awesome_motion", Icons.Outlined.AutoAwesomeMotion),
        DimensionIconOption("auto_delete", Icons.Outlined.AutoDelete),
        DimensionIconOption("auto_fix_high", Icons.Outlined.AutoFixHigh),
        DimensionIconOption("auto_fix_normal", Icons.Outlined.AutoFixNormal),
        DimensionIconOption("auto_fix_off", Icons.Outlined.AutoFixOff),
        DimensionIconOption("auto_graph", Icons.Outlined.AutoGraph),
        DimensionIconOption("auto_mode", Icons.Outlined.AutoMode),
        DimensionIconOption("autorenew", Icons.Outlined.Autorenew),
        DimensionIconOption("auto_stories", Icons.Outlined.AutoStories),
        DimensionIconOption("baby_changing_station", Icons.Outlined.BabyChangingStation),
        DimensionIconOption("badge", Icons.Outlined.Badge),
        DimensionIconOption("bakery_dining", Icons.Outlined.BakeryDining),
        DimensionIconOption("balcony", Icons.Outlined.Balcony),
        DimensionIconOption("ballot", Icons.Outlined.Ballot),
        DimensionIconOption("bar_chart", Icons.Outlined.BarChart),
        DimensionIconOption("batch_prediction", Icons.Outlined.BatchPrediction),
        DimensionIconOption("bathroom", Icons.Outlined.Bathroom),
        DimensionIconOption("bathtub", Icons.Outlined.Bathtub),
        DimensionIconOption("beach_access", Icons.Outlined.BeachAccess),
        DimensionIconOption("bed", Icons.Outlined.Bed),
        DimensionIconOption("bedroom_baby", Icons.Outlined.BedroomBaby),
        DimensionIconOption("bedroom_child", Icons.Outlined.BedroomChild),
        DimensionIconOption("bedroom_parent", Icons.Outlined.BedroomParent),
        DimensionIconOption("bedtime", Icons.Outlined.Bedtime),
        DimensionIconOption("bedtime_off", Icons.Outlined.BedtimeOff),
        DimensionIconOption("beenhere", Icons.Outlined.Beenhere),
        DimensionIconOption("bento", Icons.Outlined.Bento),
        DimensionIconOption("bike_scooter", Icons.Outlined.BikeScooter),
        DimensionIconOption("biotech", Icons.Outlined.Biotech),
        DimensionIconOption("blender", Icons.Outlined.Blender),
        DimensionIconOption("blind", Icons.Outlined.Blind),
        DimensionIconOption("blinds", Icons.Outlined.Blinds),
        DimensionIconOption("blinds_closed", Icons.Outlined.BlindsClosed),
        DimensionIconOption("bloodtype", Icons.Outlined.Bloodtype),
        DimensionIconOption("blur_circular", Icons.Outlined.BlurCircular),
        DimensionIconOption("blur_linear", Icons.Outlined.BlurLinear),
        DimensionIconOption("blur_off", Icons.Outlined.BlurOff),
        DimensionIconOption("blur_on", Icons.Outlined.BlurOn),
        DimensionIconOption("bookmark_add", Icons.Outlined.BookmarkAdd),
        DimensionIconOption("bookmark_added", Icons.Outlined.BookmarkAdded),
        DimensionIconOption("bookmark_remove", Icons.Outlined.BookmarkRemove),
        DimensionIconOption("bookmarks", Icons.Outlined.Bookmarks),
        DimensionIconOption("book_online", Icons.Outlined.BookOnline),
        DimensionIconOption("border_all", Icons.Outlined.BorderAll),
        DimensionIconOption("border_bottom", Icons.Outlined.BorderBottom),
        DimensionIconOption("border_clear", Icons.Outlined.BorderClear),
        DimensionIconOption("border_color", Icons.Outlined.BorderColor),
        DimensionIconOption("border_horizontal", Icons.Outlined.BorderHorizontal),
        DimensionIconOption("border_inner", Icons.Outlined.BorderInner),
        DimensionIconOption("border_left", Icons.Outlined.BorderLeft),
        DimensionIconOption("border_right", Icons.Outlined.BorderRight),
        DimensionIconOption("border_style", Icons.Outlined.BorderStyle),
        DimensionIconOption("border_top", Icons.Outlined.BorderTop),
        DimensionIconOption("boy", Icons.Outlined.Boy),
        DimensionIconOption("breakfast_dining", Icons.Outlined.BreakfastDining),
        DimensionIconOption("brightness1", Icons.Outlined.Brightness1),
        DimensionIconOption("brightness2", Icons.Outlined.Brightness2),
        DimensionIconOption("brightness3", Icons.Outlined.Brightness3),
        DimensionIconOption("brightness4", Icons.Outlined.Brightness4),
        DimensionIconOption("brightness5", Icons.Outlined.Brightness5),
        DimensionIconOption("brightness6", Icons.Outlined.Brightness6),
        DimensionIconOption("brightness7", Icons.Outlined.Brightness7),
        DimensionIconOption("brightness_auto", Icons.Outlined.BrightnessAuto),
        DimensionIconOption("brightness_high", Icons.Outlined.BrightnessHigh),
        DimensionIconOption("brightness_low", Icons.Outlined.BrightnessLow),
        DimensionIconOption("brightness_medium", Icons.Outlined.BrightnessMedium),
        DimensionIconOption("brunch_dining", Icons.Outlined.BrunchDining),
        DimensionIconOption("bubble_chart", Icons.Outlined.BubbleChart),
        DimensionIconOption("bungalow", Icons.Outlined.Bungalow),
        DimensionIconOption("burst_mode", Icons.Outlined.BurstMode),
        DimensionIconOption("bus_alert", Icons.Outlined.BusAlert),
        DimensionIconOption("business", Icons.Outlined.Business),
        DimensionIconOption("business_center", Icons.Outlined.BusinessCenter),
        DimensionIconOption("cabin", Icons.Outlined.Cabin),
        DimensionIconOption("cable", Icons.Outlined.Cable),
        DimensionIconOption("cached", Icons.Outlined.Cached),
        DimensionIconOption("cake", Icons.Outlined.Cake),
        DimensionIconOption("calculate", Icons.Outlined.Calculate),
        DimensionIconOption("calendar_month", Icons.Outlined.CalendarMonth),
        DimensionIconOption("calendar_today", Icons.Outlined.CalendarToday),
        DimensionIconOption("camera", Icons.Outlined.Camera),
        DimensionIconOption("camera_alt", Icons.Outlined.CameraAlt),
        DimensionIconOption("camera_enhance", Icons.Outlined.CameraEnhance),
        DimensionIconOption("camera_front", Icons.Outlined.CameraFront),
        DimensionIconOption("camera_rear", Icons.Outlined.CameraRear),
        DimensionIconOption("camera_roll", Icons.Outlined.CameraRoll),
        DimensionIconOption("cameraswitch", Icons.Outlined.Cameraswitch),
        DimensionIconOption("cancel", Icons.Outlined.Cancel),
        DimensionIconOption("cancel_presentation", Icons.Outlined.CancelPresentation),
        DimensionIconOption("candlestick_chart", Icons.Outlined.CandlestickChart),
        DimensionIconOption("car_crash", Icons.Outlined.CarCrash),
        DimensionIconOption("card_membership", Icons.Outlined.CardMembership),
        DimensionIconOption("card_travel", Icons.Outlined.CardTravel),
        DimensionIconOption("carpenter", Icons.Outlined.Carpenter),
        DimensionIconOption("car_rental", Icons.Outlined.CarRental),
        DimensionIconOption("car_repair", Icons.Outlined.CarRepair),
        DimensionIconOption("cases", Icons.Outlined.Cases),
        DimensionIconOption("casino", Icons.Outlined.Casino),
        DimensionIconOption("catching_pokemon", Icons.Outlined.CatchingPokemon),
        DimensionIconOption("celebration", Icons.Outlined.Celebration),
        DimensionIconOption("center_focus_strong", Icons.Outlined.CenterFocusStrong),
        DimensionIconOption("chair", Icons.Outlined.Chair),
        DimensionIconOption("chair_alt", Icons.Outlined.ChairAlt),
        DimensionIconOption("chalet", Icons.Outlined.Chalet),
        DimensionIconOption("change_history", Icons.Outlined.ChangeHistory),
        DimensionIconOption("chat", Icons.Outlined.Chat),
        DimensionIconOption("chat_bubble", Icons.Outlined.ChatBubble),
        DimensionIconOption("chat_bubble_outline", Icons.Outlined.ChatBubbleOutline),
        DimensionIconOption("chevron_left", Icons.Outlined.ChevronLeft),
        DimensionIconOption("chevron_right", Icons.Outlined.ChevronRight),
        DimensionIconOption("child_friendly", Icons.Outlined.ChildFriendly),
        DimensionIconOption("chrome_reader_mode", Icons.Outlined.ChromeReaderMode),
        DimensionIconOption("church", Icons.Outlined.Church),
        DimensionIconOption("class", Icons.Outlined.Class),
        DimensionIconOption("clean_hands", Icons.Outlined.CleanHands),
        DimensionIconOption("clear_all", Icons.Outlined.ClearAll),
        DimensionIconOption("co2", Icons.Outlined.Co2),
        DimensionIconOption("coffee", Icons.Outlined.Coffee),
        DimensionIconOption("coffee_maker", Icons.Outlined.CoffeeMaker),
        DimensionIconOption("collections", Icons.Outlined.Collections),
        DimensionIconOption("colorize", Icons.Outlined.Colorize),
        DimensionIconOption("color_lens", Icons.Outlined.ColorLens),
        DimensionIconOption("commit", Icons.Outlined.Commit),
        DimensionIconOption("commute", Icons.Outlined.Commute),
        DimensionIconOption("compare", Icons.Outlined.Compare),
        DimensionIconOption("compost", Icons.Outlined.Compost),
        DimensionIconOption("confirmation_number", Icons.Outlined.ConfirmationNumber),
        DimensionIconOption("connecting_airports", Icons.Outlined.ConnectingAirports),
        DimensionIconOption("connect_without_contact", Icons.Outlined.ConnectWithoutContact),
        DimensionIconOption("construction", Icons.Outlined.Construction),
        DimensionIconOption("contact_emergency", Icons.Outlined.ContactEmergency),
        DimensionIconOption("contactless", Icons.Outlined.Contactless),
        DimensionIconOption("contact_page", Icons.Outlined.ContactPage),
        DimensionIconOption("contacts", Icons.Outlined.Contacts),
        DimensionIconOption("contact_support", Icons.Outlined.ContactSupport),
        DimensionIconOption("content_copy", Icons.Outlined.ContentCopy),
        DimensionIconOption("content_cut", Icons.Outlined.ContentCut),
        DimensionIconOption("content_paste", Icons.Outlined.ContentPaste),
        DimensionIconOption("content_paste_go", Icons.Outlined.ContentPasteGo),
        DimensionIconOption("content_paste_off", Icons.Outlined.ContentPasteOff),
        DimensionIconOption("contrast", Icons.Outlined.Contrast),
        DimensionIconOption("control_camera", Icons.Outlined.ControlCamera),
        DimensionIconOption("control_point", Icons.Outlined.ControlPoint),
        DimensionIconOption("control_point_duplicate", Icons.Outlined.ControlPointDuplicate),
        DimensionIconOption("cookie", Icons.Outlined.Cookie),
        DimensionIconOption("co_present", Icons.Outlined.CoPresent),
        DimensionIconOption("copy_all", Icons.Outlined.CopyAll),
        DimensionIconOption("copyright", Icons.Outlined.Copyright),
        DimensionIconOption("coronavirus", Icons.Outlined.Coronavirus),
        DimensionIconOption("corporate_fare", Icons.Outlined.CorporateFare),
        DimensionIconOption("countertops", Icons.Outlined.Countertops),
        DimensionIconOption("credit_card", Icons.Outlined.CreditCard),
        DimensionIconOption("crib", Icons.Outlined.Crib),
        DimensionIconOption("crisis_alert", Icons.Outlined.CrisisAlert),
        DimensionIconOption("cruelty_free", Icons.Outlined.CrueltyFree),
        DimensionIconOption("css", Icons.Outlined.Css),
        DimensionIconOption("currency_bitcoin", Icons.Outlined.CurrencyBitcoin),
        DimensionIconOption("currency_exchange", Icons.Outlined.CurrencyExchange),
        DimensionIconOption("currency_franc", Icons.Outlined.CurrencyFranc),
        DimensionIconOption("currency_lira", Icons.Outlined.CurrencyLira),
        DimensionIconOption("currency_pound", Icons.Outlined.CurrencyPound),
        DimensionIconOption("currency_ruble", Icons.Outlined.CurrencyRuble),
        DimensionIconOption("currency_rupee", Icons.Outlined.CurrencyRupee),
        DimensionIconOption("currency_yen", Icons.Outlined.CurrencyYen),
        DimensionIconOption("currency_yuan", Icons.Outlined.CurrencyYuan),
        DimensionIconOption("curtains", Icons.Outlined.Curtains),
        DimensionIconOption("curtains_closed", Icons.Outlined.CurtainsClosed),
        DimensionIconOption("cyclone", Icons.Outlined.Cyclone),
        DimensionIconOption("dangerous", Icons.Outlined.Dangerous),
        DimensionIconOption("dashboard", Icons.Outlined.Dashboard),
        DimensionIconOption("dashboard_customize", Icons.Outlined.DashboardCustomize),
        DimensionIconOption("deblur", Icons.Outlined.Deblur),
        DimensionIconOption("dehaze", Icons.Outlined.Dehaze),
        DimensionIconOption("delete_forever", Icons.Outlined.DeleteForever),
        DimensionIconOption("delete_outline", Icons.Outlined.DeleteOutline),
        DimensionIconOption("delete_sweep", Icons.Outlined.DeleteSweep),
        DimensionIconOption("density_large", Icons.Outlined.DensityLarge),
        DimensionIconOption("density_medium", Icons.Outlined.DensityMedium),
        DimensionIconOption("density_small", Icons.Outlined.DensitySmall),
        DimensionIconOption("departure_board", Icons.Outlined.DepartureBoard),
        DimensionIconOption("description", Icons.Outlined.Description),
        DimensionIconOption("design_services", Icons.Outlined.DesignServices),
        DimensionIconOption("desktop_mac", Icons.Outlined.DesktopMac),
        DimensionIconOption("details", Icons.Outlined.Details),
        DimensionIconOption("developer_board", Icons.Outlined.DeveloperBoard),
        DimensionIconOption("developer_board_off", Icons.Outlined.DeveloperBoardOff),
        DimensionIconOption("devices", Icons.Outlined.Devices),
        DimensionIconOption("devices_fold", Icons.Outlined.DevicesFold),
        DimensionIconOption("devices_other", Icons.Outlined.DevicesOther),
        DimensionIconOption("device_thermostat", Icons.Outlined.DeviceThermostat),
        DimensionIconOption("device_unknown", Icons.Outlined.DeviceUnknown),
        DimensionIconOption("dialpad", Icons.Outlined.Dialpad),
        DimensionIconOption("diamond", Icons.Outlined.Diamond),
        DimensionIconOption("difference", Icons.Outlined.Difference),
        DimensionIconOption("dining", Icons.Outlined.Dining),
        DimensionIconOption("dinner_dining", Icons.Outlined.DinnerDining),
        DimensionIconOption("directions", Icons.Outlined.Directions),
        DimensionIconOption("directions_bike", Icons.Outlined.DirectionsBike),
        DimensionIconOption("directions_boat", Icons.Outlined.DirectionsBoat),
        DimensionIconOption("directions_boat_filled", Icons.Outlined.DirectionsBoatFilled),
        DimensionIconOption("directions_bus", Icons.Outlined.DirectionsBus),
        DimensionIconOption("directions_bus_filled", Icons.Outlined.DirectionsBusFilled),
        DimensionIconOption("directions_car", Icons.Outlined.DirectionsCar),
        DimensionIconOption("directions_walk", Icons.Outlined.DirectionsWalk),
    )

    private val optionsByKey: Map<String, DimensionIconOption> = options.associateBy { it.key }
    private val keyAliases: Map<String, String> = mapOf("people" to "groups")
    /**
     * Performs the default icon key for dimension id.
     */
    fun defaultIconKeyForDimensionId(dimensionId: String?): String {
        val normalizedId = dimensionId?.trim().orEmpty()
        val canonicalId = DimensionTaxonomyCatalog.fromCanonicalId(normalizedId)?.id
        DimensionTaxonomyCatalog.fromCanonicalId(canonicalId)?.let { return it.defaultIconKey }
        return when (dimensionId) {
            LifeDimension.CAREER_WORK.id -> "work"
            LifeDimension.HEALTH_WELLNESS.id -> "favorite"
            LifeDimension.RELATIONSHIPS.id -> "groups"
            LifeDimension.PERSONAL_GROWTH.id -> "trending_up"
            LifeDimension.FINANCIAL.id -> "account_balance_wallet"
            LifeDimension.SPIRITUAL.id -> "self_improvement"
            LifeDimension.RECREATION.id -> "sports_esports"
            LifeDimension.LEARNING.id -> "menu_book"
            LifeDimension.CONTRIBUTION.id -> "volunteer_activism"
            else -> "category"
        }
    }
    /**
     * Returns the result
     */
    fun resolve(key: String?, dimensionId: String? = null): DimensionIconOption {
        val normalized = key?.trim()?.takeIf { it.isNotEmpty() } ?: defaultIconKeyForDimensionId(dimensionId)
        val canonicalKey = keyAliases[normalized] ?: normalized
        return optionsByKey[canonicalKey] ?: run {
            val fallbackKey = defaultIconKeyForDimensionId(dimensionId)
            loggerOrNull()?.w(
                "DimensionIconCatalog.resolve",
                "Unknown dimension icon key; using fallback",
                mapOf("requestedKey" to normalized, "fallbackKey" to fallbackKey, "dimensionId" to (dimensionId ?: "none")),
            )
            optionsByKey.getValue(fallbackKey)
        }
    }
}
